<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>Tanks.Sim</AssemblyName>
    <RootNamespace>Tanks.Sim</RootNamespace>
    <TargetFramework>netstandard2.1</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>10.0</LangVersion>
    <ImplicitUsings>disable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>false</CheckForOverflowUnderflow>
    <DefineConstants>$(DefineConstants);NOT_UNITY</DefineConstants>
    <NoWarn>$(NoWarn);CS0164</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\..\..\Assets\Tanks\Sim\**\*.cs">
      <Link>Sim\%(RecursiveDir)%(Filename)%(Extension)</Link>
    </Compile>
  </ItemGroup>

</Project>

