<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>Tanks.Protocol.Driver</AssemblyName>
    <RootNamespace>Tanks.Net</RootNamespace>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\src\Tanks.Protocol.csproj" />
    <ProjectReference Include="..\..\Net\src\Tanks.Net.csproj" />
  </ItemGroup>

</Project>
